import Foundation

extension DeviceAction.ActionType {
    var icon: String {
        switch self {
        case .tap, .doubleTap, .longPress: return "hand.tap.fill"
        case .swipe, .dragDrop: return "hand.draw.fill"
        case .pinch: return "arrow.up.left.and.arrow.down.right"
        case .scroll: return "scroll.fill"
        case .goHome: return "house.fill"
        case .goBack: return "chevron.left"
        case .openAppSwitcher: return "rectangle.stack.fill"
        case .openNotificationCenter: return "bell.fill"
        case .openControlCenter: return "switch.2"
        case .openApp, .closeApp, .forceQuitApp: return "app.fill"
        case .typeText, .clearField, .injectKeystrokes, .submitForm: return "keyboard.fill"
        case .selectAll, .copy, .paste: return "doc.on.doc.fill"
        case .dictate: return "mic.fill"
        case .spotlight: return "magnifyingglass"
        case .webSearch: return "globe"
        case .appStoreSearch: return "bag.fill"
        case .mapSearch: return "map.fill"
        case .youtubeSearch: return "play.rectangle.fill"
        case .sendIMessage, .sendWhatsApp: return "message.fill"
        case .sendEmail: return "envelope.fill"
        case .makeCall: return "phone.fill"
        case .facetime: return "video.fill"
        case .playMusic, .pauseMusic: return "music.note"
        case .nextTrack: return "forward.fill"
        case .prevTrack: return "backward.fill"
        case .setVolume: return "speaker.wave.3.fill"
        case .takePhoto: return "camera.fill"
        case .recordVideo: return "video.circle.fill"
        case .recordScreen: return "record.circle"
        case .setBrightness: return "sun.max.fill"
        case .toggleWifi: return "wifi"
        case .toggleBluetooth: return "wave.3.right"
        case .toggleAirplane: return "airplane"
        case .toggleDarkMode: return "moon.fill"
        case .toggleLowPower: return "battery.25"
        case .toggleAutoLock: return "lock.rotation"
        case .toggleDoNotDisturb: return "moon.zzz.fill"
        case .setWallpaper: return "photo.fill"
        case .createNote: return "note.text"
        case .createReminder: return "bell.badge.fill"
        case .createCalendarEvent: return "calendar.badge.plus"
        case .setAlarm: return "alarm.fill"
        case .setTimer: return "timer"
        case .startStopwatch: return "stopwatch.fill"
        case .openFile, .downloadFile: return "doc.fill"
        case .shareFile, .airdrop: return "square.and.arrow.up.fill"
        case .lockScreen: return "lock.fill"
        case .screenshot: return "camera.viewfinder"
        case .restartSpringboard: return "arrow.clockwise"
        case .openURL: return "link"
        case .launchSiri: return "mic.circle.fill"
        case .openSettings: return "gear"
        case .runShortcut: return "bolt.fill"
        case .wait: return "clock.fill"
        case .think: return "brain"
        case .speak: return "speaker.wave.2.fill"
        case .verify: return "eye.fill"
        case .askUser: return "questionmark.circle.fill"
        case .loop: return "arrow.2.squarepath"
        case .abort: return "xmark.octagon.fill"
        }
    }

    var displayName: String {
        switch self {
        case .tap: return "Tap"
        case .doubleTap: return "Double Tap"
        case .longPress: return "Long Press"
        case .swipe: return "Swipe"
        case .pinch: return "Pinch"
        case .scroll: return "Scroll"
        case .dragDrop: return "Drag & Drop"
        case .goHome: return "Go Home"
        case .goBack: return "Go Back"
        case .openAppSwitcher: return "App Switcher"
        case .openNotificationCenter: return "Notification Center"
        case .openControlCenter: return "Control Center"
        case .openApp: return "Open App"
        case .closeApp: return "Close App"
        case .forceQuitApp: return "Force Quit"
        case .typeText: return "Type Text"
        case .clearField: return "Clear Field"
        case .selectAll: return "Select All"
        case .copy: return "Copy"
        case .paste: return "Paste"
        case .dictate: return "Dictate"
        case .injectKeystrokes: return "Type"
        case .submitForm: return "Submit"
        case .spotlight: return "Spotlight Search"
        case .webSearch: return "Web Search"
        case .appStoreSearch: return "App Store Search"
        case .mapSearch: return "Map Search"
        case .youtubeSearch: return "YouTube Search"
        case .sendIMessage: return "Send iMessage"
        case .sendWhatsApp: return "Send WhatsApp"
        case .sendEmail: return "Send Email"
        case .makeCall: return "Make Call"
        case .facetime: return "FaceTime"
        case .playMusic: return "Play Music"
        case .pauseMusic: return "Pause"
        case .nextTrack: return "Next Track"
        case .prevTrack: return "Previous Track"
        case .setVolume: return "Set Volume"
        case .takePhoto: return "Take Photo"
        case .recordVideo: return "Record Video"
        case .recordScreen: return "Record Screen"
        case .setBrightness: return "Set Brightness"
        case .toggleWifi: return "Toggle WiFi"
        case .toggleBluetooth: return "Toggle Bluetooth"
        case .toggleAirplane: return "Airplane Mode"
        case .toggleDarkMode: return "Dark Mode"
        case .toggleLowPower: return "Low Power Mode"
        case .toggleAutoLock: return "Auto-Lock"
        case .toggleDoNotDisturb: return "Do Not Disturb"
        case .setWallpaper: return "Set Wallpaper"
        case .createNote: return "Create Note"
        case .createReminder: return "Create Reminder"
        case .createCalendarEvent: return "Calendar Event"
        case .setAlarm: return "Set Alarm"
        case .setTimer: return "Set Timer"
        case .startStopwatch: return "Stopwatch"
        case .openFile: return "Open File"
        case .downloadFile: return "Download"
        case .shareFile: return "Share"
        case .airdrop: return "AirDrop"
        case .lockScreen: return "Lock Screen"
        case .screenshot: return "Screenshot"
        case .restartSpringboard: return "Restart"
        case .openURL: return "Open URL"
        case .launchSiri: return "Siri"
        case .openSettings: return "Settings"
        case .runShortcut: return "Run Shortcut"
        case .wait: return "Wait"
        case .think: return "Thinking"
        case .speak: return "Speaking"
        case .verify: return "Verifying"
        case .askUser: return "Question"
        case .loop: return "Continue"
        case .abort: return "Abort"
        }
    }
}
